trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: 'Install dependencies'

  - script: yarn run build
    displayName: 'Compile TypeScript and Build'

  - script: yarn run test:ci
    displayName: 'Run jest unit tests'
