name: ng-deploy-oss-unit-tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: npm install

      - name: Compile
        run: npm run build

      - name: Test
        env:
          CI: true
        run: npm run test:ci
