name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: build
        run: yarn run build

      - name: test
        run: yarn run test:ci
