name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: test
        uses: borales/actions-yarn@v4
        with:
          cmd: test:ci
